// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv8RT2o00LVyA1XgUBRK_x_BbqnsFqBmk',
    appId: '1:1049793808873:web:32bc2e50122c0be1f02378',
    messagingSenderId: '1049793808873',
    projectId: 'formente-9cdd6',
    authDomain: 'formente-9cdd6.firebaseapp.com',
    storageBucket: 'formente-9cdd6.appspot.com',
    measurementId: 'G-ZPGTP0220Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuD3ITekOZpstHQAxZ1yJTEYOcBH6e4m4',
    appId: '1:1049793808873:android:5ee0bccd28d99636f02378',
    messagingSenderId: '1049793808873',
    projectId: 'formente-9cdd6',
    storageBucket: 'formente-9cdd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDusfeG4vlnhoUiXEPBQfA8i2muHRZcmE8',
    appId: '1:1049793808873:ios:f98f33c9c3c4205df02378',
    messagingSenderId: '1049793808873',
    projectId: 'formente-9cdd6',
    storageBucket: 'formente-9cdd6.appspot.com',
    androidClientId: '1049793808873-9d114aic6i32ucj0j77i2rvllnirv8ge.apps.googleusercontent.com',
    iosClientId: '1049793808873-o532ej4ed9fdsbb1183f0m3t4rsjjnt9.apps.googleusercontent.com',
    iosBundleId: 'com.citizenfive.formente',
  );
}
